In [1]:
import numpy as np

In [3]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [4]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [8]:
# no hidden layer weights
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.60453609],
        [ 0.40806355]]), array([-0.98663898]))

In [9]:
# forward propagation without any hidden layer
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[ 0.27157645],
       [ 0.35926045],
       [ 0.16921864],
       [ 0.2344932 ]])

In [10]:
# one hidden layer weights
wh = 2* np.random.random((2, 2)) - 1
bh = 2* np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1,1)) - 1

In [11]:
# forward propagation with one hidden layer
output0 = X
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + bo)
output

array([[ 0.56526468],
       [ 0.53414874],
       [ 0.52175282],
       [ 0.49666483]])